# SPDX-FileCopyrightText: 2021 Peter Magnusson <me@kmpm.se>
#
# SPDX-License-Identifier: CC0-1.0
name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  # workflow_dispatch:
  
jobs:
  test:
    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        # can we compile
        run: go build -v ./...
      - name: Test
        # run any tests
        run: go test -v ./...    
  lint:
    strategy:
      matrix:
        go: [1.19]
        os: [ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        # https://github.com/golangci/golangci-lint-action
        with:
          args: --timeout=3m
      
      - name: REUSE Compliance check
        uses: fsfe/reuse-action@v1
